76 get matrix
qulacs/scaluq pull request #85
Opened 2024-03-28 10:07 UTC by Glacialte

各ゲートにget_matrixメソッドを追加しました

2024-04-02 00:42 UTC, Glacialte commented on qulacs/gate/gate_one_qubit.hpp
> +    }
ありがとうございます、修正しました...

2024-04-02 00:43 UTC, Glacialte commented on qulacs/util/utility.hpp
> +KOKKOS_INLINE_FUNCTION std::optional<ComplexMatrix> get_pauli_matrix(PauliOperator pauli) {
inlineに修正しました

2024-04-02 00:44 UTC, Glacialte commented on qulacs/types.hpp
> +using CPPCTYPE = std::complex<double>;
確かにそうですね、StdComplexに修正しておきました

2024-04-02 02:18 UTC, Glacialte commented
defined but not used warningが出ていたtests/util/util.hpp内のmake_SqrtX関数などを修正しました。
static修飾子が付いている関数が警告を出していましたが、内部リンケージを持たせる必要性がないと思うので他の関数と同じくinline修飾子だけにしています。

2024-04-09 01:51 UTC, gandalfr-KY approved these changes
大丈夫そうです！ありがとうございます

2024-04-09 03:11 UTC, KowerKoint requested changes

2024-04-09 03:11 UTC, KowerKoint commented on qulacs/gate/gate_pauli.cpp
> +    mat = cos(_angle / 2) * ComplexMatrix::Identity(mat.rows(), mat.cols()) +
本家と違ってe^{-i angle/2 P}で実装してるはずなので角度を(-_angle/2)にする

2024-04-09 03:11 UTC, KowerKoint commented on qulacs/gate/gate_pauli.cpp
> +    std::complex<double> imag_unit(0, 1);
imag_unitの型を`StdComplex`としておくべき？

2024-04-12 03:49 UTC, KowerKoint commented on qulacs/gate/gate_one_qubit.hpp
> +        mat << 1., 0, 0, std::exp(1i * _phi) * std::exp(1i * _lambda);
U2の行列表記違いそう

2024-04-16 00:14 UTC, KowerKoint approved these changes
OKです。
ありがとうございます。

2024-04-16 02:02 UTC, merged